# Generated by Django 5.1.6 on 2025-03-05 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'FAN',
                'verbose_name_plural': 'FANLAR',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fan')),
            ],
            options={
                'verbose_name': 'STUDENT',
                'verbose_name_plural': 'STUDENTS',
                'ordering': ['-pk'],
            },
        ),
    ]
